/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@class NSString;

__attribute__((visibility("hidden")))
@interface _UIAutologgingDeallocSentinel : NSObject
{
    BOOL _called;
    NSString *_message;
}

@property(nonatomic) BOOL called; // @synthesize called=_called;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
- (void)dealloc;

@end

