/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
__attribute__((visibility("hidden")))
@interface _UICollectionViewTrackedValueItem : NSObject
{
    double _timeStamp;
    float _value;
}

@property(nonatomic) float value; // @synthesize value=_value;
@property(nonatomic) double timeStamp; // @synthesize timeStamp=_timeStamp;

@end

