/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class NSLayoutConstraint, NSString, UIButton, UILabel, _UIBackdropView, _UITextFieldRoundedRectBackgroundViewNeue;

@interface _UIContentUnavailableView : UIView
{
    unsigned int _style;
    NSString *_title;
    _UIBackdropView *_backdrop;
    UIView *_containerView;
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    UIButton *_actionButton;
    _UITextFieldRoundedRectBackgroundViewNeue *_buttonBackground;
    NSLayoutConstraint *titleToMessageConstraint;
    NSLayoutConstraint *messageToButtonConstraint;
    UIView *_fromSnapshot;
    UIView *_toSnapshot;
    struct CGSize _fromSnapshotSize;
    NSString *_message;
    NSString *_buttonTitle;
    id _buttonAction;
}

@property(copy, nonatomic) id buttonAction; // @synthesize buttonAction=_buttonAction;
@property(copy, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void)tintColorDidChange;
- (void)windowDidRotateNotification:(id)arg1;
- (void)windowWillAnimateRotateNotification:(id)arg1;
- (void)windowWillRotateNotification:(id)arg1;
- (void)didMoveToWindow;
- (void)updateConstraints;
- (void)_actionButtonPressed:(id)arg1;
- (void)_updateViewHierarchy;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 style:(unsigned int)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

