/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UITapGestureRecognizer.h>

__attribute__((visibility("hidden")))
@interface _UIDismissCurlUpTapGestureRecognizer : UITapGestureRecognizer
{
    float _curlUpDY;
}

@property(nonatomic, setter=_setCurlUpDY:) float _curlUpDY; // @synthesize _curlUpDY;
- (BOOL)_delegateShouldReceiveTouch:(id)arg1;
- (BOOL)canBePreventedByGestureRecognizer:(id)arg1;

@end

