/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage, UIImageView, _UILegibilitySettings;

@interface _UILegibilityView : UIView
{
    BOOL _hidesImage;
    _UILegibilitySettings *_settings;
    UIImage *_image;
    UIImage *_shadowImage;
    float _strength;
    UIImageView *_imageView;
    UIImageView *_shadowImageView;
}

@property(retain, nonatomic) UIImageView *shadowImageView; // @synthesize shadowImageView=_shadowImageView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) BOOL hidesImage; // @synthesize hidesImage=_hidesImage;
@property(nonatomic) float strength; // @synthesize strength=_strength;
@property(retain, nonatomic) UIImage *shadowImage; // @synthesize shadowImage=_shadowImage;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) _UILegibilitySettings *settings; // @synthesize settings=_settings;
- (void)layoutSubviews;
- (void)updateForChangedSettings:(id)arg1;
- (void)setSettings:(id)arg1 image:(id)arg2 shadowImage:(id)arg3;
- (void)setStyle:(int)arg1 image:(id)arg2 shadowImage:(id)arg3;
- (void)setImage:(id)arg1 shadowImage:(id)arg2;
- (struct CGSize)sizeThatFits;
@property(readonly, nonatomic) int style; // @dynamic style;
- (void)dealloc;
- (id)initWithSettings:(id)arg1 strength:(float)arg2 image:(id)arg3 shadowImage:(id)arg4;
- (id)initWithSettings:(id)arg1 strength:(float)arg2 image:(id)arg3;
- (id)initWithStyle:(int)arg1 image:(id)arg2 shadowImage:(id)arg3;
- (id)initWithStyle:(int)arg1 image:(id)arg2;

@end

