/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIViewController.h>

@class _UIDefinitionValue;

__attribute__((visibility("hidden")))
@interface _UILongDefinitionViewController : UIViewController
{
    _UIDefinitionValue *_definitionValue;
}

- (void)viewDidAppear:(BOOL)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithDefinitionValue:(id)arg1;

@end

