/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/_UILegibilityView.h>

@class CAFilter, NSString, UIFont;

@interface _UILegibilityLabel : _UILegibilityView
{
    NSString *_string;
    UIFont *_font;
    CAFilter *_imageColorFilter;
    CAFilter *_shadowImageColorFilter;
    int _options;
}

@property(nonatomic) int options; // @synthesize options=_options;
@property(retain, nonatomic) CAFilter *shadowImageColorFilter; // @synthesize shadowImageColorFilter=_shadowImageColorFilter;
@property(retain, nonatomic) CAFilter *imageColorFilter; // @synthesize imageColorFilter=_imageColorFilter;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(copy, nonatomic) NSString *string; // @synthesize string=_string;
- (void)setSettings:(id)arg1 image:(id)arg2 shadowImage:(id)arg3;
- (void)updateForChangedSettings:(id)arg1;
- (id)colorAddMatrixValueForColor:(id)arg1;
- (void)updateImage;
@property(readonly, nonatomic) float baselineOffset;
- (id)drawingColor;
@property(readonly, nonatomic) BOOL usesColorFilters;
@property(readonly, nonatomic) BOOL usesSecondaryColor;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)dealloc;
- (id)initWithSettings:(id)arg1 strength:(float)arg2 string:(id)arg3 font:(id)arg4 options:(int)arg5;
- (id)initWithSettings:(id)arg1 strength:(float)arg2 string:(id)arg3 font:(id)arg4;

@end

