/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIViewController.h>

@class NSMutableArray, UIView, _UIModalItem;

@interface _UIModalItemsPresentingViewController : UIViewController
{
    NSMutableArray *_items;
    NSMutableArray *_itemsViews;
    UIView *_backgroundView;
    _UIModalItem *_currentItem;
    UIView *_currentItemView;
    id _itemsTransitionCompletion;
    UIView *_dimmingView;
    struct CGRect _keyboardFrame;
    float _keyboardHeight;
    BOOL _isInTransition;
    _UIModalItem *_itemBeingPresented;
    _UIModalItem *_itemBeingDismissed;
}

@property(retain, nonatomic) _UIModalItem *itemBeingPresented; // @synthesize itemBeingPresented=_itemBeingPresented;
@property(retain, nonatomic) _UIModalItem *itemBeingDismissed; // @synthesize itemBeingDismissed=_itemBeingDismissed;
@property(nonatomic) _UIModalItem *currentItem; // @synthesize currentItem=_currentItem;
@property(nonatomic) BOOL isInTransition; // @synthesize isInTransition=_isInTransition;
- (void)_showItem:(id)arg1 animated:(BOOL)arg2 undimmSpotlight:(BOOL)arg3;
- (void)_showDimmingView:(BOOL)arg1 animated:(BOOL)arg2;
- (void)_hideAnimated:(BOOL)arg1 dimmSpotlight:(BOOL)arg2;
- (void)_hide;
- (void)_showDimmingViewAnimated:(BOOL)arg1;
- (void)_hideDimmingViewAnimated:(BOOL)arg1;
- (void)_dismissItem:(id)arg1 andPresentItem:(id)arg2 animated:(BOOL)arg3 completion:(id)arg4;
- (void)_dismissItem:(id)arg1 andPresentItem:(id)arg2 animated:(BOOL)arg3 completion:(id)arg4 keepDimmingView:(void)arg5;
- (void)_applyPresentingAnimationEndingStateForModalItem:(id)arg1 view:(id)arg2 forceCenter:(BOOL)arg3;
- (void)_applyPresentingAnimationEndingStateForModalItem:(id)arg1 view:(id)arg2;
- (void)_applyDismissingAnimationEndingStateForModalItem:(id)arg1 view:(id)arg2;
- (void)_applyPresentingAnimationStartingStateForModalItem:(id)arg1 view:(id)arg2;
- (id)_createViewForItem:(id)arg1;
- (void)_dismissMe:(id)arg1 animated:(BOOL)arg2;
- (void)hideModalItem:(id)arg1 animated:(BOOL)arg2;
- (void)displayModalItem:(id)arg1 animated:(BOOL)arg2;
- (void)_hideItem:(id)arg1 animated:(BOOL)arg2;
- (void)didReceiveMemoryWarning;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (BOOL)wantsFullScreenLayout;
- (void)keyboardChanged:(id)arg1;
- (void)keyfirstResponderChanged:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;
- (id)initWithModalItemType:(int)arg1;

@end

