/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
NSCoding.hNSCopying.h
__attribute__((visibility("hidden")))
@interface _UIMotionEffectAcceleratedOutputRange : NSObject <NSCoding, NSCopying>
{
    struct UIOffset _referenceOffset;
    struct CGPoint _referenceAcceleration;
    struct CGPoint _acceleration;
}

@property(readonly, nonatomic) struct CGPoint acceleration; // @synthesize acceleration=_acceleration;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (void)reset;
- (struct UIOffset)acceleratedOutputForViewerOffset:(struct UIOffset)arg1 accelerationBoostFactor:(struct CGPoint)arg2;
- (void)setAcceleration:(struct CGPoint)arg1 fixingOutputForViewerOffset:(struct UIOffset)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

