/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import <UIKit/UITableViewDataSource.h> 
UITableViewDelegate.hUITextFieldDelegate.h
@class NSMutableArray, UIButton, UILabel, UITableView, UITextField, UIViewController, _UIModalItem, _UIModalItemsPresentingViewController;

@interface _UIModalItemContentView : UIView <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
{
    _UIModalItem *_modalItem;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_messageLabel;
    UITextField *_loginTextField;
    UITextField *_passwordTextField;
    NSMutableArray *_otherButtons;
    UIViewController *_accessoryViewController;
    struct CGSize _accessoryViewControllerSize;
    UIView *_accessoryViewControllerContrainerView;
    struct CGSize _actualViewControllerSize;
    UIButton *_cancelButton;
    UIButton *_defaultButton;
    int _cancelButtonIndex;
    int _defaultButtonIndex;
    UITableView *_buttonTable;
    struct CGSize _presentingSize;
    _UIModalItemsPresentingViewController *_presentingViewController;
    struct CGSize _maxSize;
}

@property(readonly, nonatomic) UITableView *buttonTable; // @synthesize buttonTable=_buttonTable;
@property(readonly, nonatomic) int defaultButtonIndex; // @synthesize defaultButtonIndex=_defaultButtonIndex;
@property(readonly, nonatomic) int cancelButtonIndex; // @synthesize cancelButtonIndex=_cancelButtonIndex;
@property(retain, nonatomic) UIButton *defaultButton; // @synthesize defaultButton=_defaultButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(readonly, nonatomic) UIView *accessoryViewControllerContrainerView; // @synthesize accessoryViewControllerContrainerView=_accessoryViewControllerContrainerView;
@property(readonly, nonatomic) struct CGSize accessoryViewControllerSize; // @synthesize accessoryViewControllerSize=_accessoryViewControllerSize;
@property(readonly, nonatomic) UIViewController *accessoryViewController; // @synthesize accessoryViewController=_accessoryViewController;
@property(readonly, nonatomic) UITextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(readonly, nonatomic) UITextField *loginTextField; // @synthesize loginTextField=_loginTextField;
@property(readonly, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(readonly, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) struct CGSize actualViewControllerSize; // @synthesize actualViewControllerSize=_actualViewControllerSize;
@property(nonatomic) struct CGSize maxSize; // @synthesize maxSize=_maxSize;
@property(nonatomic) _UIModalItemsPresentingViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
@property(nonatomic) struct CGSize presentingSize; // @synthesize presentingSize=_presentingSize;
@property(nonatomic) _UIModalItem *modalItem; // @synthesize modalItem=_modalItem;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)dealloc;
- (void)textFieldValueDidChange:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)layout;
- (void)_createViewControllerContentView;
- (void)_createAndConfigureTextFieldsForInputStyle:(int)arg1;
- (void)_createAndConfigureMessageLabel;
- (void)_createAndConfigureSubtitleLabel;
- (void)_createAndConfigureTitleLabel;
- (void)_createAndConfigureButtonTable;

@end

