/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIAnimation.h>

__attribute__((visibility("hidden")))
@interface _UIOldSliderAnimation : UIAnimation
{
    float _startValue;
    float _endValue;
    BOOL _sendAction;
}

- (void)setProgress:(float)arg1;

@end

