/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@class CPBitmapStore;

__attribute__((visibility("hidden")))
@interface _UIStatusBarCache : NSObject
{
    CPBitmapStore *_store;
}

+ (id)sharedInstance;
- (id)_groupForIdiom:(int)arg1 scale:(float)arg2;
- (void)cacheImage:(id)arg1 named:(id)arg2 forGroup:(id)arg3;
- (void)cacheImage:(id)arg1 named:(id)arg2 idiom:(int)arg3 scale:(float)arg4;
- (void)cacheImage:(id)arg1 named:(id)arg2;
- (BOOL)_canCacheImages;
- (id)imageNamed:(id)arg1 forGroup:(id)arg2 withScale:(float)arg3;
- (id)imageNamed:(id)arg1 idiom:(int)arg2 scale:(float)arg3;
- (id)imageNamed:(id)arg1;
- (void)dealloc;
- (id)init;

@end

