/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
__attribute__((visibility("hidden")))
@interface _UIStatusBarStateStackInfo : NSObject
{
    int _statusBarOrientationWithoutHost;
    float _statusBarHeightWithoutHost;
    int _hostPID;
}

@property int hostPID; // @synthesize hostPID=_hostPID;
@property float statusBarHeightWithoutHost; // @synthesize statusBarHeightWithoutHost=_statusBarHeightWithoutHost;
@property int statusBarOrientationWithoutHost; // @synthesize statusBarOrientationWithoutHost=_statusBarOrientationWithoutHost;

@end

