/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/_UITextFieldRoundedRectBackgroundViewNeueAlt.h>

@class CAShapeLayer;

__attribute__((visibility("hidden")))
@interface _UITextFieldPasscodeCutoutBackground : _UITextFieldRoundedRectBackgroundViewNeueAlt
{
    CAShapeLayer *_lighteningOutline;
    float _outlineAlpha;
}

+ (id)_fillColor:(BOOL)arg1;
+ (id)_strokeColor:(BOOL)arg1;
- (void)_updatePath;
- (id)customPath;
- (void)dealloc;
@property(nonatomic) float outlineAlpha;
- (id)initWithFrame:(struct CGRect)arg1 active:(BOOL)arg2;

@end

