/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UITextFieldBackgroundView.h>

@class UIBezierPath, UIColor;

@interface _UITextFieldRoundedRectBackgroundViewNeueAlt : UITextFieldBackgroundView
{
    BOOL _customStrokeColor;
    BOOL _customFillColor;
    float _cornerRadius;
    UIBezierPath *_customPath;
}

+ (Class)layerClass;
@property(copy, nonatomic) UIBezierPath *customPath; // @synthesize customPath=_customPath;
@property(nonatomic) float cornerRadius; // @synthesize cornerRadius=_cornerRadius;
- (BOOL)_shouldAnimatePropertyWithKey:(id)arg1;
- (void)setEnabled:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setActive:(BOOL)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setBounds:(struct CGRect)arg1;
@property(nonatomic) float lineWidth;
- (void)setLineWidth:(float)arg1 updatePath:(BOOL)arg2;
@property(retain, nonatomic) UIColor *fillColor;
@property(retain, nonatomic) UIColor *strokeColor;
- (void)_updatePath;
- (float)_pixelAlignment;
- (float)_pathInset;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 active:(BOOL)arg2;
- (id)_layer;
- (id)_fillColor:(BOOL)arg1;
- (id)_strokeColor:(BOOL)arg1;

@end

