/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
XPCProxyTarget.h_UIViewServiceSession_HostInterface.h
@class NSObject<OS_dispatch_queue>, _UIAsyncInvocation;

__attribute__((visibility("hidden")))
@interface _UIViewServiceSessionConnectionCatcher : NSObject <_UIViewServiceSession_HostInterface, XPCProxyTarget>
{
    NSObject<OS_dispatch_queue> *_queue;
    id _continuation;
    BOOL _isInvalidated;
    _UIAsyncInvocation *_invalidationInvocation;
    int __automatic_invalidation_retainCount;
    BOOL __automatic_invalidation_invalidated;
}

+ (id)awaitRequestThen:(id)arg1;
- (void)dealloc;
- (id)proxy:(id)arg1 detailedSignatureForSelector:(SEL)arg2;
- (id)invalidate;
- (void)__requestConnectionToDeputyOfType:(id)arg1 withReplyHandler:(id)arg2;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (unsigned int)retainCount;
- (oneway void)release;
- (id)retain;
- (int)__automatic_invalidation_logic;

@end

