/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/_UITargetedProxy.h>

_UIViewServiceDeputy.h_UIViewServiceUIBehaviorInterface.h
@class _UIAsyncInvocation;

__attribute__((visibility("hidden")))
@interface _UIViewControllerControlMessageDeputy : _UITargetedProxy <_UIViewServiceDeputy, _UIViewServiceUIBehaviorInterface>
{
    _UIAsyncInvocation *_invalidationInvocation;
    int __automatic_invalidation_retainCount;
    BOOL __automatic_invalidation_invalidated;
}

+ (id)proxyWithTarget:(id)arg1;
+ (id)XPCInterface;
- (void)_invalidateUnconditionallyThen:(id)arg1;
- (id)invalidate;
- (void)__prepareForDisconnectionWithCompletionHandler:(id)arg1;
- (void)dealloc;
- (id)_queue;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (unsigned int)retainCount;
- (oneway void)release;
- (id)retain;
- (int)__automatic_invalidation_logic;

@end

