/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@protocol _UIViewServiceDeputyRotationDelegate <NSObject>
- (void)finishRotation;
- (void)rotateToInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1;
- (void)setHostedWindow:(id)arg1;
@end

