/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
_UIViewServiceProxy_ReplyAwaiting.h
@class NSLock, _UIViewServiceReplyAwaitingTrampoline;

__attribute__((visibility("hidden")))
@interface _UIViewServiceReplyAwaitingProxy : NSObject <_UIViewServiceProxy_ReplyAwaiting>
{
    id _target;
    _UIViewServiceReplyAwaitingTrampoline *_trampoline;
    NSLock *_trampolineLock;
}

+ (id)proxyWithTarget:(id)arg1;
- (id)_awaitingReply;
- (void)dealloc;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (BOOL)respondsToSelector:(SEL)arg1;

@end

