/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <WebCore/DOMHTMLInputElement.h> 

@interface DOMHTMLInputElement (UIWebInteraction)
- (BOOL)nodeCanBecomeFirstResponder;
- (BOOL)isLikelyToBeginPageLoad;
- (BOOL)isAssistedDateType;
@end

