/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <MobileCoreServices/LSDocumentProxy.h> 

@interface LSDocumentProxy (LSResourceProxyIconPrivate)
- (CDStruct_9b4cf30b *)_iconVariantDefinitions:(id)arg1;
- (struct CGSize)_defaultStyleSize:(id)arg1;
@end

