/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIColor.h>

__attribute__((visibility("hidden")))
@interface NSColor : UIColor
{
}

+ (id)colorWithCalibratedWhite:(float)arg1 alpha:(float)arg2;
+ (id)colorWithCalibratedRed:(float)arg1 green:(float)arg2 blue:(float)arg3 alpha:(float)arg4;
- (id)initWithCoder:(id)arg1;

@end

