/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <CoreFoundation/NSDateComponents.h> 

@interface NSDateComponents (NSCalendarUnit)
+ (id)_ui_namesForComponents:(unsigned int)arg1;
+ (unsigned int)_ui_largerComponentsRelativeToComponent:(unsigned int)arg1;
+ (unsigned int)_ui_smallerComponentsRelativeToComponent:(unsigned int)arg1;
+ (unsigned int)smaller:(BOOL)arg1 componentsRelativeToComponent:(unsigned int)arg2;
- (void)_ui_setComponents:(id)arg1;
- (void)_ui_setValue:(int)arg1 forComponent:(unsigned int)arg2;
- (int)_ui_valueForComponent:(unsigned int)arg1;
- (id)_ui_conciseDescription;
@end

