/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSIndexPath.h> 

@interface NSIndexPath (UITableView)
+ (id)indexPathForRow:(int)arg1 inSection:(int)arg2;
@property(readonly, nonatomic) int row;
@property(readonly, nonatomic) int section;
@end

