/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@interface NSObject (UIAccessibilityAction)
- (BOOL)accessibilityActivate;
- (BOOL)accessibilityPerformMagicTap;
- (BOOL)accessibilityPerformEscape;
- (BOOL)accessibilityScroll:(int)arg1;
- (void)accessibilityDecrement;
- (void)accessibilityIncrement;
@end

