/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@interface UIAcceleration : NSObject
{
    double timestamp;
    double x;
    double y;
    double z;
}

@property(nonatomic) double z; // @synthesize z;
@property(nonatomic) double y; // @synthesize y;
@property(nonatomic) double x; // @synthesize x;
@property(nonatomic) double timestamp; // @synthesize timestamp;
- (id)description;

@end

