/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/_UIPopoverStandardChromeView.h>

__attribute__((visibility("hidden")))
@interface UIActivityViewPopoverBackgroundView : _UIPopoverStandardChromeView
{
}

+ (struct UIEdgeInsets)contentViewInsets;
+ (void)useNormalContentViewInsets:(BOOL)arg1;
- (float)_shadowOpacity;

@end

