/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
__attribute__((visibility("hidden")))
@interface UIControlTargetAction : NSObject
{
    id _target;
    SEL _action;
    int _eventMask;
    BOOL _cancelled;
}

@property(nonatomic) BOOL cancelled; // @synthesize cancelled=_cancelled;

@end

