/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
_UIAppearanceContainer.h
__attribute__((visibility("hidden")))
@interface UIDeviceAppearanceContainer : NSObject <_UIAppearanceContainer>
{
}

+ (BOOL)_preventsAppearanceProxyCustomization;
- (id)_appearanceGuideClass;
- (id)_appearanceContainer;

@end

