/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIDictationView.h>

__attribute__((visibility("hidden")))
@interface UIDictationiPhoneLayoutView : UIDictationView
{
}

- (BOOL)isShowing;
- (void)returnToKeyboard;
- (void)finishReturnToKeyboard;
- (void)layoutSubviews;
- (void)setState:(int)arg1;
- (void)setRenderConfig:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)doneButtonTitleForLightBackground:(BOOL)arg1;

@end

