/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIDOMHTMLOptionPickerCell.h>

__attribute__((visibility("hidden")))
@interface UIDOMHTMLOptGroupCell : UIDOMHTMLOptionPickerCell
{
}

- (void)layoutSubviews;
- (float)labelWidthForBounds:(struct CGRect)arg1;
- (id)initWithHTMLOptGroupNode:(id)arg1;

@end

