/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIViewController.h>

@class UIWindow;

__attribute__((visibility("hidden")))
@interface UIFileUploadFallbackRootViewController : UIViewController
{
    UIWindow *_window;
}

- (void)detach;
- (void)attach;
- (void)dealloc;
- (id)initWithWindow:(id)arg1;

@end

