/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UISharedArtwork.h>

_UISharedArtworkResolving.h
__attribute__((visibility("hidden")))
@interface UIImageTableArtwork : UISharedArtwork <_UISharedArtworkResolving>
{
}

+ (id)sharedInstance;
+ (void)initialize;
- (void)cacheImage:(id)arg1 name:(id)arg2 index:(unsigned int)arg3;

@end

