/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIInputViewTransition.h>

__attribute__((visibility("hidden")))
@interface UIInputViewRotateTransition : UIInputViewTransition
{
}

- (BOOL)shouldRecomputeEndFrame;
- (BOOL)shouldCompleteOnSuspend;
- (BOOL)fadeAccessoryView;
- (void)postNotificationsForTransitionEnd;
- (void)postNotificationsForTransitionStart;
- (BOOL)subsumesTransition:(id)arg1;

@end

