/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKBRenderFactoryHWR_Portrait.h>

__attribute__((visibility("hidden")))
@interface UIKBRenderFactoryHWR_Landscape : UIKBRenderFactoryHWR_Portrait
{
}

- (void)setupLayoutSegments;
- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;
- (float)spaceKeyFontSize;
- (struct CGPoint)spaceKeyTextOffset;
- (struct CGPoint)deleteGlyphOffset;
- (BOOL)deleteKeyAdjacentToCandidates;
- (struct UIEdgeInsets)handwritingAreaInsets;
- (float)handwritingGradientStartLocation;

@end

