/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKBRenderFactory.h>

__attribute__((visibility("hidden")))
@interface UIKBRenderFactory_Candidates : UIKBRenderFactory
{
}

- (id)traitsForEdgeGradientWithSize:(struct CGSize)arg1;
- (id)traitsForSortControlBackgroundWithSize:(struct CGSize)arg1;
- (id)traitsForEmptyExtendedPane:(struct CGSize)arg1 rowHeight:(float)arg2 idiomPad:(BOOL)arg3;
- (id)traitsForExtendedCellSize:(struct CGSize)arg1 highlighted:(BOOL)arg2 groupHeader:(BOOL)arg3 edges:(unsigned int)arg4;
- (id)traitsForHWRCellSize:(struct CGSize)arg1 highlighted:(BOOL)arg2;
- (id)traitsForCellSize:(struct CGSize)arg1 highlighted:(BOOL)arg2 edges:(BOOL)arg3;
- (id)initWithRenderConfig:(id)arg1;

@end

