/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKBHandwritingPointFIFO.h>

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface UIKBHandwritingBoxcarFilterPointFIFO : UIKBHandwritingPointFIFO
{
    NSMutableArray *_prevPoints;
    unsigned int _width;
}

@property(nonatomic) unsigned int width; // @synthesize width=_width;
@property(retain, nonatomic) NSMutableArray *prevPoints; // @synthesize prevPoints=_prevPoints;
- (void)clear;
- (void)flush;
- (void)addPoint:(struct CGPoint)arg1;
- (void)emitAveragedPoint;
- (void)dealloc;
- (id)initWithFIFO:(id)arg1 width:(unsigned int)arg2;

@end

