/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@class NSData, NSString, UIImage;

__attribute__((visibility("hidden")))
@interface UIKBRenderer : NSObject
{
    struct CGContext *_cachingContext;
    BOOL _opaque;
    struct CGContext *_ctx;
    float _scale;
    int _renderFlags;
    NSString *_cacheKey;
    UIImage *_renderedImage;
    struct CGSize _size;
}

+ (struct CGContext *)imageContextWithSize:(struct CGSize)arg1 scale:(float)arg2 opaque:(BOOL)arg3 invert:(BOOL)arg4;
+ (id)rendererWithContext:(struct CGContext *)arg1 withSize:(struct CGSize)arg2 withScale:(float)arg3 opaque:(BOOL)arg4 renderFlags:(int)arg5;
@property(retain, nonatomic) NSString *cacheKey; // @synthesize cacheKey=_cacheKey;
@property(readonly, nonatomic) int renderFlags; // @synthesize renderFlags=_renderFlags;
@property(readonly, nonatomic) BOOL opaque; // @synthesize opaque=_opaque;
@property(readonly, nonatomic) float scale; // @synthesize scale=_scale;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
- (id)pathForSplitGeometry:(id)arg1;
- (id)pathForFlickPopupGeometries:(id)arg1;
- (id)pathForFlickGeometry:(id)arg1;
- (id)pathForRenderGeometry:(id)arg1;
- (void)addPathForSplitGeometry:(id)arg1;
- (void)addPathForFlickPopupGeometries:(id)arg1;
- (void)addPathForFlickGeometry:(id)arg1;
- (void)addPathForRenderGeometry:(id)arg1;
- (void)addPathForTraits:(id)arg1 displayRect:(struct CGRect *)arg2;
- (void)addRoundRect:(struct CGRect)arg1 radius:(float)arg2 corners:(unsigned int)arg3;
- (void)renderKeyPathContents:(id)arg1 withTraits:(id)arg2;
- (void)drawShiftPath:(BOOL)arg1 weight:(float)arg2 transform:(struct CGAffineTransform)arg3 color:(struct CGColor *)arg4;
- (void)drawPath:(struct CGPath *)arg1 weight:(float)arg2 transform:(struct CGAffineTransform)arg3 color:(struct CGColor *)arg4 fill:(BOOL)arg5;
- (struct CGPath *)_deleteGlyphPaths;
- (struct CGPath *)_thickShiftGlyphPath;
- (struct CGPath *)_thinShiftGlyphPath;
- (void)renderKeyStringContents:(id)arg1 withTraits:(id)arg2;
- (BOOL)_drawKeyString:(id)arg1 inRect:(struct CGRect)arg2 withStyle:(id)arg3;
- (BOOL)_drawSingleSymbol:(id)arg1 inRect:(struct CGRect)arg2 withStyle:(id)arg3;
- (void)renderKeyImageContents:(id)arg1 withTraits:(id)arg2;
- (void)_drawKeyImage:(id)arg1 inRect:(struct CGRect)arg2 withStyle:(id)arg3;
- (void)_renderVariantsFromKeyContents:(id)arg1 withTraits:(id)arg2;
- (void)renderKeyContents:(id)arg1 withTraits:(id)arg2;
- (void)renderBackgroundTraits:(id)arg1;
- (BOOL)loadCachedImageForHashString:(id)arg1;
- (struct CGContext *)_contextForCacheImageSize:(struct CGSize)arg1;
- (void)renderBackgroundTraits:(id)arg1 allowCaching:(BOOL)arg2;
- (void)_drawLinearGradient:(id)arg1 inRect:(struct CGRect)arg2;
- (void)renderShadowEffect:(id)arg1 withTraits:(id)arg2;
- (void)renderEdgeEffect:(id)arg1 withTraits:(id)arg2;
@property(readonly, nonatomic) NSData *contextData;
@property(readonly, nonatomic) UIImage *renderedImage; // @synthesize renderedImage=_renderedImage;
@property(readonly, nonatomic) struct CGContext *context; // @synthesize context=_ctx;
- (void)ensureContext;
- (void)dealloc;
- (id)initWithContext:(struct CGContext *)arg1 withSize:(struct CGSize)arg2 withScale:(float)arg3 opaque:(BOOL)arg4 renderFlags:(int)arg5;

@end

