/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

UIKBCacheableView.h
@class CALayer, NSString, UIKBRenderConfig, UIKBTree, UIKeyboardMenuView;

__attribute__((visibility("hidden")))
@interface UIKBKeyView : UIView <UIKBCacheableView>
{
    UIKBTree *m_keyplane;
    UIKBTree *m_key;
    struct CGRect m_drawFrame;
    struct __CFBoolean *m_allowsCaching;
    UIKBRenderConfig *m_renderConfig;
    CALayer *_keyBorders;
    CALayer *_keyBackgrounds;
    CALayer *_keyCaps;
    BOOL _usesControlOpacities;
    BOOL _renderAsMask;
    UIKeyboardMenuView *_popupMenu;
}

@property(nonatomic) BOOL renderAsMask; // @synthesize renderAsMask=_renderAsMask;
@property(nonatomic) BOOL usesControlOpacities; // @synthesize usesControlOpacities=_usesControlOpacities;
@property(nonatomic) UIKeyboardMenuView *popupMenu; // @synthesize popupMenu=_popupMenu;
@property(retain, nonatomic) UIKBRenderConfig *renderConfig; // @synthesize renderConfig=m_renderConfig;
@property(nonatomic) struct CGRect drawFrame; // @synthesize drawFrame=m_drawFrame;
@property(readonly, nonatomic) UIKBTree *key; // @synthesize key=m_key;
@property(readonly, nonatomic) UIKBTree *keyplane; // @synthesize keyplane=m_keyplane;
- (id)_generateBackdropMaskImage;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawContentsOfRenderers:(id)arg1;
@property(readonly, nonatomic) BOOL keepNonPersistent;
@property(readonly, nonatomic) float cachedWidth;
@property(readonly, nonatomic) BOOL cacheDeferable;
- (void)displayLayer:(id)arg1;
- (id)_setupLayerIfNoLayer:(id)arg1 withContents:(id)arg2;
@property(readonly) int cachedRenderFlags;
- (id)cacheKeysForRenderFlags:(id)arg1;
@property(readonly, nonatomic) NSString *cacheKey;
@property(readonly, nonatomic) struct UIEdgeInsets displayInsets;
- (void)dimKeyCaps:(float)arg1 duration:(float)arg2;
- (void)_applyAppearanceInvocations;
- (int)textEffectsVisibilityLevel;
- (void)dealloc;
- (void)updateForKeyplane:(id)arg1 key:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 keyplane:(id)arg2 key:(id)arg3;

@end

