/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKBRenderFactory.h>

__attribute__((visibility("hidden")))
@interface UIKBRenderFactory10Key : UIKBRenderFactory
{
}

- (id)activeControlKeyTraits;
- (id)controlKeyTraits;
- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;
- (struct CGPoint)dictationKeyTextOffset;
- (struct CGPoint)globeKeyTextOffset;
- (struct CGPoint)abcKeyTextOffset;
- (float)interkeyGapsCenterXOfKeyplaneFrame:(struct CGRect)arg1;
- (struct UIEdgeInsets)topEdgeAdjustmentInsets;
- (id)_preferredScriptFontForRendering:(int)arg1;
- (id)displayContentsForKey:(id)arg1;
- (id)backgroundTraitsForKeyplane:(id)arg1;

@end

