/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKBRenderFactoryiPhone.h>

__attribute__((visibility("hidden")))
@interface UIKBRenderFactoryiPad : UIKBRenderFactoryiPhone
{
}

- (void)_customizeTraits:(id)arg1 forPopupForKey:(id)arg2 withRenderConfig:(id)arg3 keycapsFontName:(id)arg4;
- (void)setupLayoutSegments;
- (float)_row4ControlSegmentWidth;
- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;
- (id)variantGeometriesForGeometry:(id)arg1 variantCount:(unsigned int)arg2;
- (float)defaultVariantSizeThreshold;
- (struct CGSize)defaultVariantGeometrySize;
- (void)_customizePopupTraits:(id)arg1 forKey:(id)arg2 onKeyplane:(id)arg3;
- (struct UIEdgeInsets)variantSymbolFrameInsets;
- (struct UIEdgeInsets)variantDisplayFrameInsets;
- (BOOL)shouldClearBaseDisplayStringForVariants;
- (void)_customizeSymbolStyle:(id)arg1 forKey:(id)arg2 contents:(id)arg3;
- (struct CGPoint)dismissKeyOffset;
- (struct CGPoint)dualStringKeyOffset;
- (float)fallbackFontSize;
- (float)facemarkKeyFontSize;
- (float)emailDotKeyFontSize;
- (float)smallKanaKeyFontSize;
- (float)dismissKeyFontSize;
- (float)spaceKeyFontSize;
- (float)dictationKeyFontSize;
- (float)internationalKeyFontSize;
- (float)moreKeyFontSize;
- (float)deleteKeyFontSize;
- (float)shiftKeyFontSize;
- (float)defaultPathWeight;
- (float)fontSizeAdjustmentForNonAlphanumericKeycaps;
- (float)bottomRowDefaultFontSize;
- (float)dualStringKeyFontSizeAdjustment;
- (float)stringKeyFontSize;
- (void)_customizeGeometry:(id)arg1 forKey:(id)arg2 contents:(id)arg3;
- (id)muttitapReverseKeyImageName;
- (id)multitapCompleteKeyImageName;
- (id)dismissKeyImageName;
- (id)dictationKeyImageName;
- (id)globalKeyImageName;
- (struct CGPoint)dictationKeyOffset;
- (struct CGPoint)internationalKeyOffset;
- (float)keyInsetBottom;
- (float)symbolFrameInset;
- (struct CGRect)dismissKeySymbolFrame;
- (struct CGRect)shiftKeySymbolFrame;
- (float)dualStringKeyMiddleMargin;
- (float)keyCornerRadius;
- (id)thinKeycapsFontName;
- (id)lightKeycapsFontName;

@end

