/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

NSCopying.h#import <Foundation/NSObject.h>
@protocol UIKBRenderEffect <NSObject, NSCopying>
@property(nonatomic) float weight;
@property(readonly, nonatomic) struct CGColor *color;
@property(readonly, nonatomic) SEL renderSelector;
@property(readonly, nonatomic) BOOL renderUnder;
@property(readonly, nonatomic) BOOL isValid;
@end

