/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKBRenderFactory10Key_Landscape.h>

__attribute__((visibility("hidden")))
@interface UIKBRenderFactoryiPad10Key_Portrait : UIKBRenderFactory10Key_Landscape
{
}

- (id)_traitsForKey:(id)arg1 onKeyplane:(id)arg2;
- (void)_customizeTraits:(id)arg1 forPopupForKey:(id)arg2 withRenderConfig:(id)arg3 keycapsFontName:(id)arg4;
- (id)backgroundTraitsForKeyplane:(id)arg1;
- (struct UIEdgeInsets)topEdgeAdjustmentInsets;
- (float)controlColumnWidthFactor;
- (id)muttitapReverseKeyImageName;
- (id)multitapCompleteKeyImageName;
- (float)keyCornerRadius;
- (id)thinKeycapsFontName;
- (id)lightKeycapsFontName;

@end

