/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImageView;

__attribute__((visibility("hidden")))
@interface UIKBSplitImageView : UIView
{
    UIImageView *_fullView;
    UIImageView *_splitLeft;
    UIImageView *_splitRight;
}

- (void)setImage:(id)arg1 cachedWidth:(float)arg2 keyplane:(id)arg3;
- (void)setImage:(id)arg1 splitLeft:(id)arg2 splitRight:(id)arg3 keyplane:(id)arg4;
- (void)insertSubviewAtBottom:(id)arg1;
- (BOOL)_shouldInheritScreenScaleAsContentScaleFactor;
- (void)setAlpha:(float)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

