/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKBRenderFactoryiPadHWR_Portrait.h>

__attribute__((visibility("hidden")))
@interface UIKBRenderFactoryiPadHWR_Landscape : UIKBRenderFactoryiPadHWR_Portrait
{
}

- (float)controlColumnWidthFactor;
- (float)keyCornerRadius;
- (struct CGPoint)dismissKeyOffset;
- (float)dismissKeyFontSize;
- (float)spaceKeyFontSize;
- (float)dictationKeyFontSize;
- (float)internationalKeyFontSize;
- (float)moreKeyFontSize;
- (float)deleteKeyFontSize;

@end

