/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface UIKeyboardBackdropCornerView : UIView
{
    int _corners;
    float _radius;
}

- (id)_generateBackdropMaskImage;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateFrame:(struct CGRect)arg1 withCorners:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1 withCorners:(int)arg2;

@end

