/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface UIKeyboardCandidatePocketShadow : UIView
{
    BOOL _shadowFadesToBottom;
    float _shadowHeightGrowthFactor;
}

+ (float)width;
@property(nonatomic) BOOL shadowFadesToBottom; // @synthesize shadowFadesToBottom=_shadowFadesToBottom;
@property(nonatomic) float shadowHeightGrowthFactor; // @synthesize shadowHeightGrowthFactor=_shadowHeightGrowthFactor;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

