/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <TextInput/TIKeyboardBehaviors.h> 

__attribute__((visibility("hidden")))
@interface UIKeyboardBehaviors_Handwriting : TIKeyboardBehaviors
{
    BOOL _usesCandidateSelection;
}

@property(nonatomic) BOOL usesCandidateSelection; // @synthesize usesCandidateSelection=_usesCandidateSelection;
- (id)keyBehaviorsForState:(id)arg1;

@end

