/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIKeyboardCandidateBarCell.h>

__attribute__((visibility("hidden")))
@interface UIKeyboardCandidateBarCell_SecondaryCandidate : UIKeyboardCandidateBarCell
{
}

+ (BOOL)highlightAffectsBackground;
+ (struct UIEdgeInsets)cacheInsets;
+ (id)textColorWithHighlight:(BOOL)arg1 whiteText:(BOOL)arg2;
+ (id)font;
+ (BOOL)_preventsAppearanceProxyCustomization;
+ (id)reuseIdentifier;
- (void)drawRect:(struct CGRect)arg1;

@end

