/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@protocol UIModalViewDelegate <NSObject>

@optional
- (void)modalView:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)modalView:(id)arg1 willDismissWithButtonIndex:(int)arg2;
- (void)didPresentModalView:(id)arg1;
- (void)willPresentModalView:(id)arg1;
- (void)modalViewCancel:(id)arg1;
- (void)modalView:(id)arg1 clickedButtonAtIndex:(int)arg2;
@end

