/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIInternalEvent.h>

__attribute__((visibility("hidden")))
@interface UIMoveEvent : UIInternalEvent
{
    int _moveDirection;
}

@property(nonatomic, setter=_setMoveDirection:) int _moveDirection; // @synthesize _moveDirection;
- (void)_sendEventToResponder:(id)arg1;
- (int)type;

@end

