/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIInputViewAnimationStyle.h>

@class UINavigationControllerKeyboardAnimationStyleInfo, _UIViewControllerTransitionContext;

__attribute__((visibility("hidden")))
@interface UINavigationControllerKeyboardAnimationStyle : UIInputViewAnimationStyle
{
    BOOL _disableAlongsideView;
    _UIViewControllerTransitionContext *_context;
    UINavigationControllerKeyboardAnimationStyleInfo *_info;
}

+ (id)animationStyleWithoutAlongsideViewAnimated:(BOOL)arg1 duration:(double)arg2 outDirection:(int)arg3 context:(id)arg4;
+ (id)animationStyleAnimated:(BOOL)arg1 duration:(double)arg2 outDirection:(int)arg3 context:(id)arg4;
@property(readonly, nonatomic) UINavigationControllerKeyboardAnimationStyleInfo *info; // @synthesize info=_info;
@property(nonatomic) BOOL disableAlongsideView; // @synthesize disableAlongsideView=_disableAlongsideView;
@property(readonly, nonatomic) _UIViewControllerTransitionContext *context; // @synthesize context=_context;
- (void)launchAnimation:(id)arg1 afterStarted:(void)arg2 completion:(id)arg3 forHost:(void)arg4 fromCurrentPosition:(id)arg5;
- (void)dealloc;
- (id)initWithContext:(id)arg1;
- (BOOL)useCustomTransition;
- (BOOL)isAnimationCompleted;

@end

