/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
__attribute__((visibility("hidden")))
@interface UINavigationControllerKeyboardAnimationStyleInfo : NSObject
{
    BOOL _isAnimationCompleting;
    id _previousCompleteHandler;
}

@property(nonatomic) BOOL isAnimationCompleting; // @synthesize isAnimationCompleting=_isAnimationCompleting;
@property(copy, nonatomic) id previousCompleteHandler; // @synthesize previousCompleteHandler=_previousCompleteHandler;
- (void)dealloc;

@end

