/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UITableViewCell.h>

@class UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface UIPrintStatusJobTableViewCell : UITableViewCell
{
    UIActivityIndicatorView *_activityIndicator;
}

- (void)layoutSubviews;
@property(nonatomic) BOOL showActive;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1;

@end

