/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIWindow.h>

__attribute__((visibility("hidden")))
@interface UISoftwareDimmingWindow : UIWindow
{
    float _overlayLevel;
}

@property(nonatomic) float overlayLevel; // @synthesize overlayLevel=_overlayLevel;
- (void)updateOverlayColor;
- (BOOL)_ignoresHitTest;
- (id)initWithFrame:(struct CGRect)arg1;

@end

