/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
NSCopying.h
@class NSString;

__attribute__((visibility("hidden")))
@interface UIStatusBarComposedData : NSObject <NSCopying>
{
    CDStruct_5c1a9c4d _rawData;
    char _itemEnabled[31];
    NSString *_doubleHeightStatus;
}

@property(copy, nonatomic) NSString *doubleHeightStatus; // @synthesize doubleHeightStatus=_doubleHeightStatus;
- (void)setItem:(int)arg1 enabled:(BOOL)arg2;
- (BOOL)isItemEnabled:(int)arg1;
@property(readonly, nonatomic) CDStruct_5c1a9c4d *rawData;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithRawData:(const CDStruct_5c1a9c4d *)arg1;

@end

