/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIStatusBarNewUIForegroundStyleAttributes.h>

__attribute__((visibility("hidden")))
@interface UIStatusBarExternalForegroundStyleAttributes : UIStatusBarNewUIForegroundStyleAttributes
{
}

- (id)homeImageName;
- (float)textOffsetForStyle:(int)arg1;
- (id)makeTextFontForStyle:(int)arg1;
- (id)expandedNameForImageName:(id)arg1;
- (float)batteryAccessoryMargin;
- (struct UIEdgeInsets)edgeInsetsForBluetoothBatteryInsides;
- (struct UIEdgeInsets)edgeInsetsForBatteryInsides;
- (float)edgePadding;
- (float)standardPadding;
- (float)scale;

@end

