/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIStatusBarIndicatorItemView.h>

__attribute__((visibility("hidden")))
@interface UIStatusBarAirplaneModeItemView : UIStatusBarIndicatorItemView
{
}

- (void)setVisible:(BOOL)arg1 frame:(struct CGRect)arg2 duration:(double)arg3;
- (float)extraLeftPadding;

@end

