/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIStatusBarItemView.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface UIStatusBarTimeItemView : UIStatusBarItemView
{
    NSString *_timeString;
}

- (void)dealloc;
- (int)textStyle;
- (BOOL)cachesImage;
- (id)contentsImage;
- (BOOL)updateForNewData:(id)arg1 actions:(int)arg2;

@end

