/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface UIStatusBarForegroundStyleAttributes : NSObject
{
    float _height;
    int _legibilityStyle;
    NSMutableDictionary *_cachedFonts;
}

- (float)airplaneItemExtraMargin;
- (void)setThermalColorShadow;
- (int)legacyStyle;
- (struct CGPoint)positionForMoonMaskInBounds:(struct CGRect)arg1;
- (float)sizeForMoonMaskVisible:(BOOL)arg1;
- (id)textForNetworkType:(int)arg1;
- (float)bluetoothBatteryExtraPadding;
- (id)homeImageName;
- (id)tintColor;
- (id)textColorForStyle:(int)arg1;
- (id)makeTextFontForStyle:(int)arg1;
- (id)textFontForStyle:(int)arg1;
- (id)expandedNameForImageName:(id)arg1;
- (id)cachedImageWithText:(id)arg1 forWidth:(float)arg2 lineBreakMode:(int)arg3 letterSpacing:(float)arg4 bounds:(struct CGRect)arg5 textAlignment:(int)arg6 style:(int)arg7;
- (id)imageWithText:(id)arg1 forWidth:(float)arg2 lineBreakMode:(int)arg3 letterSpacing:(float)arg4 bounds:(struct CGRect)arg5 textAlignment:(int)arg6 style:(int)arg7 cacheImage:(BOOL)arg8 withLegibilityStyle:(int)arg9 legibilityStrength:(float)arg10;
- (id)shadowImageForImage:(id)arg1 withIdentifier:(id)arg2 forStyle:(int)arg3 withStrength:(float)arg4 cachesImage:(BOOL)arg5;
- (id)imageNamed:(id)arg1 withLegibilityStyle:(int)arg2 legibilityStrength:(float)arg3;
- (id)imageNamed:(id)arg1;
- (id)untintedImageNamed:(id)arg1;
- (id)uncachedImageNamed:(id)arg1;
- (float)shadowPadding;
- (float)edgePadding;
- (float)standardPadding;
- (float)scale;
- (void)drawTextInRect:(struct CGRect)arg1 withColor:(id)arg2 withBlock:(id)arg3;
- (void)drawText:(id)arg1 forWidth:(float)arg2 lineBreakMode:(int)arg3 letterSpacing:(float)arg4 bounds:(struct CGRect)arg5 textAlignment:(int)arg6 style:(int)arg7 textSize:(struct CGSize)arg8;
- (float)textOffsetForStyle:(int)arg1;
- (void)_drawText:(id)arg1 inRect:(struct CGRect)arg2 withFont:(id)arg3 lineBreakMode:(int)arg4 letterSpacing:(float)arg5 textAlignment:(int)arg6;
- (void)drawBluetoothBatteryInsidesWithSize:(struct CGSize)arg1 capacity:(float)arg2;
- (void)drawBatteryInsidesWithSize:(struct CGSize)arg1 capacity:(float)arg2 charging:(BOOL)arg3;
- (float)batteryAccessoryMargin;
- (int)activityIndicatorStyleWithSyncActivity:(BOOL)arg1;
- (int)legibilityStyle;
- (float)height;
- (id)uniqueIdentifier;
- (void)dealloc;
- (id)initWithHeight:(float)arg1 legibilityStyle:(int)arg2;

@end

