/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@class UIViewController;

__attribute__((visibility("hidden")))
@interface UIStoryboardScene : NSObject
{
    UIViewController *sceneViewController;
}

@property(retain, nonatomic) UIViewController *sceneViewController; // @synthesize sceneViewController;
- (void)dealloc;

@end

