/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIStatusBarNewUIStyleAttributes.h>

__attribute__((visibility("hidden")))
@interface UIStatusBarExternalStyleAttributes : UIStatusBarNewUIStyleAttributes
{
}

- (BOOL)shouldShowInternalItemType:(int)arg1 withScreenCapabilities:(id)arg2;
- (Class)foregroundStyleClass;
- (id)backgroundImageName;
- (float)heightForMetrics:(int)arg1;
- (int)idiom;

@end

