/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIStoryboardSegue.h>

__attribute__((visibility("hidden")))
@interface UIStoryboardPushSegue : UIStoryboardSegue
{
    int _destinationContainmentContext;
    int _splitViewControllerIndex;
}

@property(nonatomic) int splitViewControllerIndex; // @synthesize splitViewControllerIndex=_splitViewControllerIndex;
@property(nonatomic) int destinationContainmentContext; // @synthesize destinationContainmentContext=_destinationContainmentContext;
- (void)perform;

@end

