/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class CALayer;

__attribute__((visibility("hidden")))
@interface UITableViewCellContentView : UIView
{
    CALayer *_mask;
}

+ (id)classFallbacksForKeyedArchiver;
- (void)dealloc;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
@property(retain, nonatomic) CALayer *mask;
- (id)_cell;

@end

