/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@class UITabBarItem, UIView;

__attribute__((visibility("hidden")))
@interface UITabBarItemProxy : NSObject
{
    UITabBarItem *_item;
    UIView *_view;
}

- (id)view;
- (id)item;
- (void)dealloc;
- (void)setSelected:(BOOL)arg1;
- (id)initWithItem:(id)arg1 inTabBar:(id)arg2;

@end

