/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@class UIColor;

__attribute__((visibility("hidden")))
@interface UITableViewCellUnhighlightedState : NSObject
{
    BOOL _opaque;
    BOOL _highlighted;
    UIColor *_backgroundColor;
}

@property(retain) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property BOOL highlighted; // @synthesize highlighted=_highlighted;
@property BOOL opaque; // @synthesize opaque=_opaque;
- (void)dealloc;

@end

