/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UITextFieldLabel.h>

__attribute__((visibility("hidden")))
@interface UITextFieldCenteredLabel : UITextFieldLabel
{
    float _textXPosition;
    float _textWidth;
}

@property(nonatomic) float textWidth; // @synthesize textWidth=_textWidth;
@property(nonatomic) float textXPosition; // @synthesize textXPosition=_textXPosition;
- (BOOL)_isTextFieldCenteredLabel;

@end

