/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface UIThreePartImageView : UIView
{
    CDStruct_75b8db5d _slices;
    UIImage *_image;
}

- (void)drawRect:(struct CGRect)arg1;
- (void)setSlices:(CDStruct_75b8db5d)arg1;
- (void)setImage:(id)arg1;
- (void)dealloc;

@end

