/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSObject.h>
@class UITouch;

__attribute__((visibility("hidden")))
@interface UITouchData : NSObject
{
    struct CGPoint startTouchDownLocation;
    unsigned int lastTapCount;
    double lastTouchUpTimestamp;
    double lastTouchDownTimestamp;
    BOOL touchIsValidTap;
    UITouch *lastTouch;
}

@end

