/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

UIViewControllerAnimatedTransitioning.h
@protocol UIViewControllerAnimatedTransitioningEx <UIViewControllerAnimatedTransitioning>
- (void)setOperation:(int)arg1;
- (int)operation;
- (void)setInteractionAborted:(BOOL)arg1;
- (BOOL)interactionAborted;
- (void)setInteractionController:(id)arg1;
- (id)interactionController;
@end

