/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIWebRotatingNodePopover.h>

UIWebRotatingNodePopoverDelegate.h
__attribute__((visibility("hidden")))
@interface UIWebRotatingAccessoryPopover : UIWebRotatingNodePopover <UIWebRotatingNodePopoverDelegate>
{
}

- (void)popoverWasDismissed:(id)arg1;
- (unsigned int)popoverArrowDirections;
- (void)accessoryDone;
- (id)initWithDOMNode:(id)arg1;

@end

