/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UILongPressGestureRecognizer.h>

@class UIWebDocumentView;

__attribute__((visibility("hidden")))
@interface UIWebLongPressInSelectableRecognizer : UILongPressGestureRecognizer
{
    UIWebDocumentView *_documentView;
}

@property(nonatomic) UIWebDocumentView *documentView; // @synthesize documentView=_documentView;
- (void)setState:(int)arg1;

@end

