/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIViewController.h>

__attribute__((visibility("hidden")))
@interface UIWebDateTimePopoverViewController : UIViewController
{
    id <UIWebFormControl> _innerWebDateTimeControl;
}

@property(retain, nonatomic) id <UIWebFormControl> _innerWebDateTimeControl; // @synthesize _innerWebDateTimeControl;
- (void)loadView;
- (void)dealloc;
- (id)initWithDOMHTMLInputElement:(id)arg1 datePickerMode:(int)arg2;

@end

