/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <Foundation/NSUndoManager.h> 

__attribute__((visibility("hidden")))
@interface WebThreadSafeUndoManager : NSUndoManager
{
}

- (BOOL)_alwaysShowEditAlertView;
- (void)redo;
- (void)undo;

@end

